import Landing from '../components/Landing'
import Head from 'next/head'

export async function getStaticProps() {
   const res = await fetch(`http://127.0.0.1:1337/api/outnows`, {method: "GET"})
   const outnows = await res.json()

   return {
      props: {
         outnows,
      },
   };
}

export default function Home({outnows}) {
   return (
      <>
      <Head>
         <title>Ikaika Records - Record label, audio services, and community</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing outnows={outnows} /> 
      </>
   )
}
